# Use gunicorn as the http gateway for the server since it passes request parameters directly to the 
# server context.

FROM python:3.8.0
COPY . /app
WORKDIR /app
RUN pip install --upgrade pip && pip install -r requirements.txt
EXPOSE 80
CMD gunicorn --bind 0.0.0.0:80 app:app
