# This file contains the configuration of all the containers to be used for the project.

version: '3.8'
services:

  # Proxy
  reverse-proxy: 
    image: nginx:latest
    restart: always
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl-certs:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
    networks:
      - irene-network
  
  #################### DATABASE ####################
  irene-db: 
    image: mongo:latest
    restart: always
    # ports: 
    #   - 27017:27017 # Testing, port should not be open to the public
    environment: 
      - MONGO_INITDB_DATABASE=IReNEdb # Database name as in init-mogo.js
      - MONGO_INITDB_ROOT_USERNAME=testuser # Database root username as in init-mogo.js
      - MONGO_INITDB_ROOT_PASSWORD=testpassword # Database root password  as in init-mogo.js
    volumes:
      - database_vol:/data/db # Update to a location on disc and not a volume
    networks:
      - irene-network

  # # #################### ADMIN ####################
  admin-ui:
    restart: always
    build: 
      context: ./IReNE-admin-ui
      dockerfile: ./Dockerfile
    networks:
      - irene-network
  
  admin-server:
    restart: always
    build: 
      context: ./IReNE-admin-server
      dockerfile: ./Dockerfile
    networks:
      - irene-network

  # # #################### TellSpace ####################
  tellspace-ui:
    restart: always
    build: 
      context: ./IReNE-tellspace-ui
      dockerfile: ./Dockerfile
    networks:
      - irene-network

  
  tellspace-server:
    restart: always
    build: 
      context: ./IReNE-tellspace-server
      dockerfile: ./Dockerfile
    networks:
      - irene-network

  # # #################### SearchSpace ####################
  searchspace-ui:
    restart: always
    build: 
      context: ./IReNE-searchspace-ui
      dockerfile: ./Dockerfile
    networks:
      - irene-network
  
  searchspace-server:
    restart: always
    build: 
      context: ./IReNE-searchspace-server
      dockerfile: ./Dockerfile
    networks:
      - irene-network

  
networks:
  irene-network:

volumes:
  database_vol:
